defaults: &defaults
  working_directory: /work
  docker:
    - image: docker:17.10-git

version: 2

jobs:

  lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker version
      - run:
          name: "Lint"
          command: |
            dockerfile=dockerfiles/Dockerfile.lint
            echo "COPY . ." >> $dockerfile
            #docker build -f $dockerfile --tag cli-linter:$CIRCLE_BUILD_NUM .
            #docker run --rm cli-linter:$CIRCLE_BUILD_NUM

  test-1.9:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Unit Test GO 1.9"
          command: |
            dockerfile=dockerfiles/Dockerfile
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-builder:$CIRCLE_BUILD_NUM .
            docker run --name \
                test-$CIRCLE_BUILD_NUM cli-builder:$CIRCLE_BUILD_NUM \
                bash -c 'hack/test-unit-with-coverage'
      - run:
          name: "Upload to Codecov"
          command: |
            docker cp \
                test-$CIRCLE_BUILD_NUM:/go/src/github.com/seriousben/net-script/coverage.txt \
                coverage.txt
            apk add -U bash curl
            curl -s https://codecov.io/bash | bash || \
                echo 'Codecov failed to upload'

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test-1.9
